import Head from 'next/head'
import Header from '../components/Header'
import Herosection from '../components/Herosection'
import dynamic from 'next/dynamic'
import LastPosts from '../components/LastPosts'

export default function Home({posts}) {
  const DynamicComponentWithNoSSR = dynamic(
    () => import('../components/footer'),
    { ssr: false }
  )

  return (
    <div>
      <Head>
        <title>Moviou</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Herosection />
      <LastPosts posts={posts} />
      <DynamicComponentWithNoSSR />
    </div>
  )
}

export const getServerSideProps = async pageContext => {
  const query = encodeURIComponent('*[ _type == "post" ]');
  const url = `https://bjhivepu.api.sanity.io/v1/data/query/production?query=${query}`;
  const result = await fetch(url).then(res => res.json());

  if (!result.result || !result.result.length) {
    return {
      props: {
        posts: [],
      }
    }
  } else {
    return {
      props: {
        posts: result.result,
      }
    }
  }
};